//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int SalaryId { get; set; }
        public int EmployeeId { get; set; }
        public int CurrencyId { get; set; }
        public int AnnualAmount { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
